import Head from "next/head";
import { useEffect } from "react";
import Footer from "../components/Footer";
import Forms from "../components/Forms";
import Header from "../components/Header";
import Performances from "../components/Performances";

import { useSelector, useDispatch } from "react-redux";
import { decrement, increment, selectValue } from "../slices/filterSlice";

function Home() {
  return (
    <div className="min-h-screen flex flex-col">
      <Head>
        <title>StandUp.cz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="flex-1">
        <Performances />
      </main>
      <Footer />
    </div>
  );
}

export default Home;
